// AUTO-GENERATED by inertia-pages plugin. Do not edit.
import type app from './server'
import type { Post } from './types'

export interface PageMap {
  'About': { title: string; }
  'Home': { message: string; }
  'Posts/Index': { posts: Post[]; }
  'Posts/New': Record<string, never> | { errors: Record<string, string>; }
  'Posts/Show': { post: Post; }
}

export type PageName = keyof PageMap

declare module '@hono/inertia' {
  interface AppRegistry {
    app: typeof app
  }
  interface InertiaPages {
    'About': PageMap['About']
    'Home': PageMap['Home']
    'Posts/Index': PageMap['Posts/Index']
    'Posts/New': PageMap['Posts/New']
    'Posts/Show': PageMap['Posts/Show']
  }
}
