// AUTO-GENERATED by inertia-pages plugin. Do not edit.
import type { Post } from './types'

export interface PageMap {
  'About': { title: string; }
  'Home': { message: string; }
  'Posts/Index': { posts: Post[]; }
  'Posts/New': Record<string, never> | { errors: Record<string, string>; }
  'Posts/Show': { post: Post; }
}

export type PageName = keyof PageMap
