import { writeFileSync } from 'node:fs'
import { dirname, relative, resolve } from 'node:path'
import { Project, type CallExpression, SyntaxKind, type Type, ts } from 'ts-morph'
import type { Plugin } from 'vite'

type Options = {
  serverFile?: string
  outFile?: string
  tsConfigFilePath?: string
}

export function inertiaPagesPlugin(options: Options = {}): Plugin {
  const cwd = process.cwd()
  const serverPath = resolve(cwd, options.serverFile ?? 'app/server.ts')
  const outPath = resolve(cwd, options.outFile ?? 'app/pages.gen.ts')
  const tsConfigPath = resolve(cwd, options.tsConfigFilePath ?? 'tsconfig.app.json')

  let project: Project | null = null

  const ensureProject = () => {
    if (project) return project
    project = new Project({
      tsConfigFilePath: tsConfigPath,
      skipAddingFilesFromTsConfig: false,
    })
    return project
  }

  const formatType = (type: Type) =>
    type.getText(
      undefined,
      ts.TypeFormatFlags.NoTruncation |
        ts.TypeFormatFlags.UseSingleQuotesForStringLiteralType |
        ts.TypeFormatFlags.NoTypeReduction |
        ts.TypeFormatFlags.UseFullyQualifiedType
    )

  const collectImportedSymbols = (typeText: string) => {
    const imports = new Map<string, Set<string>>()
    const re = /import\("([^"]+)"\)\.(\w+)/g
    let match: RegExpExecArray | null
    while ((match = re.exec(typeText)) !== null) {
      const module = match[1]
      const name = match[2]
      if (!module || !name) continue
      if (!imports.has(module)) imports.set(module, new Set())
      imports.get(module)!.add(name)
    }
    return imports
  }

  const stripImportPaths = (typeText: string) => typeText.replace(/import\("[^"]+"\)\./g, '')

  const moduleSpecifierFromOutDir = (absoluteImport: string) => {
    let rel = relative(dirname(outPath), absoluteImport)
    if (!rel.startsWith('.')) rel = `./${rel}`
    return rel.replace(/\.tsx?$/, '').replaceAll('\\', '/')
  }

  const generate = () => {
    const proj = ensureProject()
    const sf = proj.getSourceFile(serverPath)
    if (!sf) {
      console.warn(`[inertia-pages] server file not found: ${serverPath}`)
      return
    }
    sf.refreshFromFileSystemSync()

    const pageMap = new Map<string, string>()
    const allImports = new Map<string, Set<string>>()

    sf.forEachDescendant((node) => {
      if (node.getKind() !== SyntaxKind.CallExpression) return
      const call = node as CallExpression
      const expr = call.getExpression()
      if (expr.getKind() !== SyntaxKind.PropertyAccessExpression) return
      const prop = expr.asKindOrThrow(SyntaxKind.PropertyAccessExpression)
      if (prop.getName() !== 'render') return

      const args = call.getArguments()
      const nameArg = args[0]
      if (!nameArg || nameArg.getKind() !== SyntaxKind.StringLiteral) return
      const name = nameArg.asKindOrThrow(SyntaxKind.StringLiteral).getLiteralValue()

      const propsArg = args[1]
      let propsTypeText: string
      if (!propsArg) {
        propsTypeText = 'Record<string, never>'
      } else {
        const type = propsArg.getType()
        const raw = formatType(type)

        const imports = collectImportedSymbols(raw)
        for (const [mod, names] of imports) {
          const spec = moduleSpecifierFromOutDir(mod)
          if (!allImports.has(spec)) allImports.set(spec, new Set())
          for (const n of names) allImports.get(spec)!.add(n)
        }
        propsTypeText = stripImportPaths(raw)
      }

      const existing = pageMap.get(name)
      if (existing && existing !== propsTypeText) {
        pageMap.set(name, `${existing} | ${propsTypeText}`)
      } else {
        pageMap.set(name, propsTypeText)
      }
    })

    const importLines = Array.from(allImports.entries())
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([spec, names]) => {
        const list = Array.from(names).sort().join(', ')
        return `import type { ${list} } from '${spec}'`
      })

    const entries = Array.from(pageMap.entries())
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([name, type]) => `  '${name}': ${type}`)

    const body = `// AUTO-GENERATED by inertia-pages plugin. Do not edit.
${importLines.join('\n')}${importLines.length ? '\n\n' : ''}export interface PageMap {
${entries.join('\n')}
}

export type PageName = keyof PageMap
`
    writeFileSync(outPath, body)
  }

  return {
    name: 'inertia-pages',
    buildStart: generate,
    configureServer(server) {
      generate()
      server.watcher.on('change', (file) => {
        if (file === serverPath) generate()
      })
      server.watcher.on('add', (file) => {
        if (file === serverPath) generate()
      })
    },
  }
}
